**Dataframes**

In [1]:
import pandas as pd

In [2]:
list_values = [5, 10, 15]

In [5]:
# dataframe from array

In [3]:
list_values

[5, 10, 15]

In [4]:
pd.DataFrame(data=list_values, columns=["values"], dtype="float")

values
0     5.0
1    10.0
2    15.0

In [6]:
# dataframe from numpy array

In [7]:
import numpy as np

In [8]:
arr_example = np.random.randint(0, 50, (4, 4))

In [9]:
arr_example

array([[ 3, 20,  3, 18],
       [12, 17, 45,  7],
       [ 9,  6, 43,  2],
       [26, 42,  1, 32]])

In [12]:
df = pd.DataFrame(arr_example, index=["a", "b", "c", "d"], columns=["Value one", "Value two", "Value three", "Value four"])

In [13]:
df.head()

Value one  Value two  Value three  Value four
a          3         20            3          18
b         12         17           45           7
c          9          6           43           2
d         26         42            1          32

In [14]:
# from dictionary

In [15]:
x = np.random.randint(0, 50, size=6)
y = np.random.randint(0, 50, size=6)
z = np.random.randint(0, 50, size=6)

In [16]:
x

array([ 0, 40, 20, 13, 34, 21])

In [17]:
dict_example = {"Value ONE": x, "Value TWO": y, "Value THREE": z}

In [18]:
dict_example

{'Value ONE': array([ 0, 40, 20, 13, 34, 21]),
 'Value TWO': array([48, 41, 15, 47, 10, 45]),
 'Value THREE': array([42, 43, 38, 33, 32, 21])}

In [21]:
df = pd.DataFrame(dict_example)

In [20]:
# properties

In [22]:
df.head()

Value ONE  Value TWO  Value THREE
0          0         48           42
1         40         41           43
2         20         15           38
3         13         47           33
4         34         10           32

In [23]:
df.tail(1)

Value ONE  Value TWO  Value THREE
5         21         45           21

In [24]:
df.columns

Index(['Value ONE', 'Value TWO', 'Value THREE'], dtype='object')

In [25]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Value ONE    6 non-null      int64
 1   Value TWO    6 non-null      int64
 2   Value THREE  6 non-null      int64
dtypes: int64(3)
memory usage: 272.0 bytes


In [27]:
df.values

array([[ 0, 48, 42],
       [40, 41, 43],
       [20, 15, 38],
       [13, 47, 33],
       [34, 10, 32],
       [21, 45, 21]])

In [28]:
type(df.values)

numpy.ndarray

In [29]:
df.shape

(6, 3)

In [30]:
df.ndim

2

In [31]:
df.size

18