**Indexing**

In [1]:
import numpy as np

In [2]:
array = np.arange(1, 11)

In [3]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
array[4]

5

In [5]:
array[-1]

10

In [6]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
array[0][1]

2

**Slicing**

In [9]:
array = np.arange(1, 20)

In [10]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
# array[start:stop:step]

In [12]:
array[1:-2:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [13]:
# 2dim arrays?

In [14]:
array = np.arange(30).reshape(6, 5)

In [15]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [16]:
# array[rowIdx, slicing row]

In [18]:
array[2, :-2]

array([10, 11, 12])

In [19]:
# all rows and certain column

In [20]:
array[:, 0]

array([ 0,  5, 10, 15, 20, 25])

In [21]:
# only first row

In [22]:
array[0]

array([0, 1, 2, 3, 4])

In [23]:
array[1:4, 0:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

**Value assignment**

In [24]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [25]:
array[0, 0] = 4

In [26]:
array

array([[ 4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [27]:
array = np.arange(20, 40)

In [28]:
array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [29]:
array[0] = 40

In [31]:
array

array([40, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [32]:
array[0:5] = 10

In [33]:
array

array([10, 10, 10, 10, 10, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [34]:
array[5:] = 40

In [35]:
array

array([10, 10, 10, 10, 10, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40])

In [36]:
# you can slice then assign

In [37]:
array

array([10, 10, 10, 10, 10, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40])

In [38]:
# fancy indices for 1-d arrays

In [39]:
array[[0, 10, 12]]

array([10, 40, 40])

In [40]:
# fancy indices for 2-d arrays

In [41]:
array = np.zeros((10, 10), dtype="int")

In [42]:
array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [43]:
array.shape

(10, 10)

In [45]:
for i in range(10):
    array[i] =  i

In [46]:
array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [47]:
indices = [1, 3, 5, 7]

In [48]:
array[indices]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [49]:
array = np.arange(1, 17).reshape(4, 4)

In [50]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [51]:
array[[0, 3], [1, 2]]

array([ 2, 15])

In [52]:
# to get 2, 15 => [r2, r15] , [c2, c15]

In [53]:
# fancy and normal indexing in practice

In [54]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
# fucking 6, 8 right now

In [56]:
array[1, [1, 3]]

array([6, 8])

In [57]:
# slicing and normal indexing

In [58]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
array[0:, [1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [60]:
array[1:3, [1,2 ]]

array([[ 6,  7],
       [10, 11]])

### Operations in numpy

**comparison operators**

In [61]:
array = np.arange(1, 11)

In [62]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [64]:
array[array > 5]

array([ 6,  7,  8,  9, 10])

In [66]:
condition = (array != 8) & (array >= 6)

In [67]:
array[condition]

array([ 6,  7,  9, 10])

**Arithmetic operator**

In [69]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
array - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [71]:
array * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [72]:
array ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [73]:
np.sqrt(100)

10.0

In [74]:
np.mod(array, 5)

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0])

In [75]:
np.sin(100)

-0.5063656411097588

In [76]:
np.sin(60)

-0.3048106211022167

In [79]:
np.sin(np.pi / 6)

0.49999999999999994

In [80]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
np.sum(array)

55

In [82]:
np.mean(array)

5.5

In [83]:
np.median(array)

5.5

In [84]:
np.min(array)

1

In [85]:
np.max(array)

10

In [86]:
np.var(array)

8.25

**Solving second degree equation**

2x + y = 5

-3x + 6y = 0

In [87]:
coef = np.array([[2, 1], [-3, 6]])

In [88]:
out = np.array([5, 0])

In [89]:
out

array([5, 0])

In [90]:
np.linalg.solve(coef, out)

array([2., 1.])